# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestant1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contestant1', to=settings.AUTH_USER_MODEL)),
                ('contestant2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('score2', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'is not started'), (3, 'ended')], default=1, null=True)),
                ('command1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command1', to='football_app.Command')),
                ('command2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='football_app.Command')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.PositiveSmallIntegerField(choices=[(1, 'championship'), (2, 'play-off')], default=1, null=True)),
                ('description', models.CharField(default=None, max_length=256, null=True)),
                ('games', models.ManyToManyField(blank=True, default=None, to='football_app.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'is not started'), (2, 'current'), (3, 'ended')], default=1, null=True)),
                ('commands', models.ManyToManyField(blank=True, default=None, to='football_app.Command')),
                ('rounds', models.ManyToManyField(blank=True, default=None, to='football_app.Round')),
            ],
        ),
    ]
