# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0002_auto_20170311_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
