# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0003_auto_20170311_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='users',
            new_name='contestants',
        ),
    ]
