# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0004_auto_20170314_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='rounds',
        ),
        migrations.AddField(
            model_name='game',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'championship'), (2, 'play-off-1/16'), (3, 'play-off-1/8'), (4, 'play-off-1/4'), (5, 'play-off-1/2'), (6, 'play-off-final'), (7, 'play-off-third-place')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='championship',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='championship', to='football_app.Round'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='playoff',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='football_app.Round'),
        ),
    ]
