# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0008_auto_20170314_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='command1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_command1', to='football_app.Command'),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'is not started'), (2, 'current'), (3, 'ended')], default=1, null=True),
        ),
    ]
