# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0014_auto_20170315_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votinglist',
            name='tournament',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='football_app.Tournament'),
        ),
    ]
